Process and PID file

diff --git a/processes_and_signals/10-process_and_pid_file b/processes_and_signals/10-process_and_pid_file
--- a/processes_and_signals/10-process_and_pid_file
+++ b/processes_and_signals/10-process_and_pid_file
@@ -1,12 +1,27 @@
 #!/usr/bin/env bash
-#signal
+
+# Function to handle cleanup
 clean_up() {
+    echo "Cleaning up and terminating..."
     rm -f /var/run/myscript.pid
     exit $?
 }
 
+# Function to handle SIGINT signal
+handle_sigint() {
+    echo "Y U no love me?!"
+}
+
 # Register clean_up function to trap signals
 trap 'clean_up' SIGTERM SIGQUIT
+trap 'handle_sigint' SIGINT
 
 # Store the PID of this script
 echo $$ > "/var/run/myscript.pid"
+
+# Display message indefinitely
+while true; do
+    echo "To infinity and beyond"
+    sleep 1
+done
+
