Highlander

diff --git a/processes_and_signals/10-process_and_pid_file b/processes_and_signals/10-process_and_pid_file
--- a/processes_and_signals/10-process_and_pid_file
+++ b/processes_and_signals/10-process_and_pid_file
@@ -1,32 +1,41 @@
 #!/usr/bin/env bash
+#function to handle SIGNTERM
+terminate() {
+    echo "I hate the kill command"
+    cleanup
+    exit 1
+}
 
-# Function to handle SIGTERM and SIGQUIT signals
-handle_signals() {
-    echo "Deleting PID file and terminating..."
+# Function to handle SIGINT signal
+interrupt() {
+    echo "Y U no love me?!"
+}
+
+# Function to handle SIGQUIT signal
+quit() {
+    echo "Received SIGQUIT signal"
+    cleanup
+    exit 1
+}
+
+# Function to clean up and exit
+cleanup() {
+    echo "Cleaning up and exiting..."
     rm -f /var/run/myscript.pid
     exit 0
 }
 
-# Function to handle SIGTERM signal
-handle_sigterm() {
-    echo "I hate the kill command"
-}
-
-# Function to handle SIGINT signal
-handle_sigint() {
-    echo "Y U no love me?!"
-}
-
 # Trap signals
-trap 'handle_signals' SIGQUIT SIGTERM
-trap 'handle_sigterm' SIGTERM
-trap 'handle_sigint' SIGINT
+trap 'terminate' SIGTERM
+trap 'interrupt' SIGINT
+trap 'quit' SIGQUIT
 
-# Write PID to file
+# Create PID file
 echo $$ > /var/run/myscript.pid
 
-# Infinite loop
+# Display message indefinitely
 while true; do
-    echo "To infinity and beyond indefinitely"
-    sleep 2
+    echo "To infinity and beyond"
+    sleep 1
 done
+
